export const STRING_CONSTANTS = {
  HEADLINE: "HEADLINE",
  PARAGRAPH: "PARAGRAPH",
  SUB_HEADLINE: "SUB HEADLINE",
  IMAGE: "IMAGE",
  BULLET_LIST: "BULLET LIST",
  TEXT: "Text",
  MEDIA: "Media",
  UNSET: "UNSET",
  ROW: "ROW",
  COLUMN: "COLUMN",
  ADD_NEW_ROW: "ADD NEW ROW",
  ADD_NEW_ELEMENT: "ADD NEW ELEMENT",
};
